sudo: required

language: node_js
node_js:
  - "8"

cache:
  directories:
    - "node_modules"

services:
  - docker

install: npm install

script: npm run build -- -p

before_deploy: "echo 'ready?'"
deploy:
  provider: heroku
  api-key:
    secure: $HEROKU_API_KEY
  on:
    branch: master
