sudo: required

language: node_js
node_js:
  - "8"

cache:
  directories:
    - "node_modules"

services:
  - docker

deploy:
  provider: heroku
  branches:
    only:
        - master
  api_key:
    secure: "YOUR ENCRYPTED API KEY"
