sudo: required

language: node_js
node_js:
  - "8"

cache:
  directories:
    - "node_modules"

services:
  - docker

deploy:
  provider: heroku
  api-key:
    secure: $HEROKU_API_KEY
  branches:
    only:
        - master
